const url = "https://ntp-forum-server.herokuapp.com";
const devUrl = "http://localhost:3000";

export const registerEndpoint = devUrl + "/register";
export const loginEndpoint = devUrl + "/login";
export const authEndpoint = devUrl + "/auth";
export const searchEndpoint = url + "/search?data=";
export const fetchForumsEndpoint = url + "/getForums";
export const createThreadEndpoint = url + "/createThread";
export const findThreadEndpoint = url + "/findThread?id=";
export const createPostEndpoint = url + "/createPost";
export const deletePostEndpoint = url + "/deletePost";
export const editPostEndpoint = url + "/editPost";
export const fetchProfilEndpoint = devUrl + "/fetchProfil?id=";
export const deleteNotificationsEndpoint = url + "/deleteNotifications";
export const fetchUserThreadsEndpoint = url + "/findUserThreads";
export const editForumEndpoint = url + "/editForum";
export const deleteForumEndpoint = url + "/deleteForum?id=";
export const createForumEndpoint = url + "/createForum";
export const closeThreadEndpoint = url + "/closeThread?id=";
export const deleteThreadEndpoint = url + "/deleteThread?id=";
export const banUserEndpoint = devUrl + "/banUser";
