const FETCH_FORUM_PENDING = "FETCH_FORUM_PENDING";
const FETCH_FORUM_SUCCESS = "FETCH_FORUM_SUCCESS";
const FETCH_FORUM_FAILED = "FETCH_FORUM_FAILED";

export default {
  FETCH_FORUM_FAILED,
  FETCH_FORUM_SUCCESS,
  FETCH_FORUM_PENDING
};
