const FETCH_THREAD_PENDING = "FETCH_THREAD_PENDING";
const FETCH_THREAD_SUCCESS = "FETCH_THREAD_SUCCESS";
const FETCH_THREAD_FAILED = "FETCH_THREAD_FAILED";

export default {
  FETCH_THREAD_PENDING,
  FETCH_THREAD_SUCCESS,
  FETCH_THREAD_FAILED
};
