const REGISTER_REQUEST_PENDING = "REGISTER_REQUEST_PENDING";
const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
const REGISTER_REQUEST_FAILED = "REGISTER_REQUEST_FAILED";
const LOGIN_REQUEST_PENDING = "LOGIN_REQUEST_PENDING";
const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
const LOGOUT = "LOGOUT";
const AUTH = "AUTH";
const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

//TEST
const FETCH_PROFIL_PENDING = "FETCH_PROFIL_PENDING";
const FETCH_PROFIL_SUCCESS = "FETCH_PROFIL_SUCCESS";
const FETCH_PROFIL_FAILED = "FETCH_PROFIL_FAILED";

export default {
  LOGIN_REQUEST_PENDING,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUEST_FAILED,
  REGISTER_REQUEST_FAILED,
  REGISTER_REQUEST_SUCCESS,
  REGISTER_REQUEST_PENDING,
  FETCH_PROFIL_FAILED,
  FETCH_PROFIL_SUCCESS,
  FETCH_PROFIL_PENDING,
  LOGOUT,
  AUTH,
  CLEAR_ERROR_MESSAGE,
};
